"$schema" = "https://schemastore.netlify.app/netlify-toml.json?"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[build]
environment = { NODE_OPTIONS = "--max-old-space-size=4096" }
command = "pnpm mk"
publish = "app/output"

